"""Build schedule.html - a self-contained, shareable snapshot of the heatmap.

Run: uv run python build_html.py
Re-run whenever schedule.json or overrides.json changes.
"""
import datetime as dt
import json
import urllib.request
from pathlib import Path

import app

HERE = Path(__file__).parent
PLOTLY_URL = "https://cdn.plot.ly/plotly-2.35.2.min.js"

TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>RA Schedule Tracker</title>
<style>
  body { margin: 0; background: #F4F6F5; font-family: -apple-system, Segoe UI, Roboto, sans-serif; color: #1a1a1a; }
  header { background: #014421; color: #fff; padding: 18px 24px; }
  header h1 { margin: 0; font-size: 20px; }
  header p { margin: 4px 0 0; font-size: 13px; opacity: .9; }
  main { max-width: 1100px; margin: 0 auto; padding: 16px 16px 48px; }
  .controls { display: flex; gap: 16px; align-items: center; margin: 8px 0 4px; font-size: 14px; }
  .controls input { font-size: 14px; padding: 4px 8px; }
  footer { text-align: center; color: #777; font-size: 12px; margin-top: 12px; }
</style>
</head>
<body>
<header>
  <h1>📅 RA Schedule Tracker</h1>
  <p>Red = no one free, green = all free. Numbers = free RAs. Orange = exam/event override.</p>
</header>
<main>
  <div class="controls">
    <label>Week of <input type="date" id="weekdate"></label>
    <span id="weeklabel"></span>
  </div>
  <div id="chart"></div>
  <footer>Snapshot generated by build_html.py from schedule.json + overrides.json.</footer>
</main>
<script>
__PLOTLY__
</script>
<script>
const D = __DATA__;
const DAY_SHORT = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
const MONTH_SHORT = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
const fmt = m => { const h = Math.floor(m / 60), mm = m % 60, h12 = h % 12 || 12;
  return String(h12).padStart(2,"0") + ":" + String(mm).padStart(2,"0") + (h < 12 ? "AM" : "PM"); };
const overlap = (a, b) => a[0] < b[1] && b[0] < a[1];
const iso = d => d.getFullYear() + "-" + String(d.getMonth()+1).padStart(2,"0") + "-" + String(d.getDate()).padStart(2,"0");
const label = d => DAY_SHORT[d.getDay()] + " " + MONTH_SHORT[d.getMonth()] + " " + d.getDate();
const STOPS = [[0,[179,48,48]],[0.5,[244,197,66]],[1,[1,68,33]]];
const cellRgb = (v, n) => {
  const pos = v / Math.max(1, n);
  for (let k = 0; k < STOPS.length - 1; k++) {
    const [p1, c1] = STOPS[k], [p2, c2] = STOPS[k+1];
    if (pos >= p1 && pos <= p2) { const t = (pos - p1) / (p2 - p1); return c1.map((a, i) => Math.round(a + (c2[i] - a) * t)); }
  }
  return STOPS[STOPS.length - 1][1];
};
const textColor = (v, ov, n) => {
  if (ov) return "#1a1a1a";
  const [r, g, b] = cellRgb(v, n);
  return 0.299*r + 0.587*g + 0.114*b < 140 ? "white" : "#1a1a1a";
};
const yLabels = D.slots.map(s => fmt(s[0]) + " to " + fmt(s[1]));
const weekOf = d => { const m = new Date(d); m.setDate(m.getDate() - ((d.getDay() + 6) % 7)); m.setHours(0,0,0,0); return m; };

function render(monday) {
  const x = [], isos = [];
  for (let j = 0; j < 7; j++) { const d = new Date(monday); d.setDate(monday.getDate() + j); x.push(label(d)); isos.push(iso(d)); }
  const z = [], hover = [], mask = [], texts = [], tcolors = [], xs = [], ys = [];
  let anyMask = false;
  for (let i = 0; i < D.slots.length; i++) {
    const zr = [], hr = [], mr = [], tr = [], cr = [];
    for (let j = 0; j < 7; j++) {
      const events = D.overrides.filter(o => o.date === isos[j] && overlap([o.start, o.end], D.slots[i]));
      const busy = D.members.filter(m => D.weekday_busy[i][j].includes(m) || events.some(e => e.person === m));
      const avail = D.members.filter(m => !busy.includes(m));
      let hv;
      if (!avail.length) hv = "No one available and Busy: " + busy.join(", ");
      else if (avail.length === D.members.length) hv = "All available";
      else hv = "Available: " + avail.join(", ") + " and Busy: " + busy.join(", ");
      hv += events.map(e => "<br>Event: " + e.event + " (" + e.person + ")").join("");
      zr.push(avail.length); hr.push(hv); tr.push(String(avail.length));
      const ov = events.length > 0; if (ov) anyMask = true;
      mr.push(ov ? 1 : null);
      cr.push(textColor(avail.length, ov, D.members.length));
      xs.push(x[j]); ys.push(yLabels[i]);
    }
    z.push(zr); hover.push(hr); mask.push(mr); texts.push(tr); tcolors.push(cr);
  }
  const data = [
    { type: "heatmap", z, x, y: yLabels, zmin: 0, zmax: Math.max(1, D.members.length),
      colorscale: [[0, "#B33030"], [0.5, "#F4C542"], [1, "#014421"]],
      customdata: hover, hovertemplate: "%{customdata}<extra></extra>",
      colorbar: { title: "Available RAs" } },
    { type: "scatter", mode: "text", x: xs, y: ys, text: texts,
      textfont: { color: tcolors, size: 11 }, hoverinfo: "skip" },
  ];
  if (anyMask) {
    data.splice(1, 0, { type: "heatmap", z: mask, x, y: yLabels, zmin: 0, zmax: 1,
      colorscale: [[0, "rgba(0,0,0,0)"], [1, "#F18A1C"]], showscale: false, hoverinfo: "skip" });
  }
  const layout = { title: "Week of " + label(monday) + ", " + monday.getFullYear(),
    yaxis: { autorange: "reversed" }, height: 650, plot_bgcolor: "#F4F6F5",
    paper_bgcolor: "white", margin: { l: 10, r: 10, t: 50, b: 10 } };
  Plotly.react("chart", data, layout);
  document.getElementById("weeklabel").textContent = "(pick any date in the week)";
}

const buildMonday = new Date(D.build_monday + "T00:00:00");
const today = new Date(buildMonday); today.setDate(today.getDate() + D.today_offset);
const input = document.getElementById("weekdate");
input.value = iso(today);
input.addEventListener("change", () => render(weekOf(new Date(input.value + "T00:00:00"))));
render(weekOf(today));
</script>
</body>
</html>
"""


def _plotly_js():
    print("downloading plotly.js ...")
    with urllib.request.urlopen(PLOTLY_URL, timeout=60) as r:
        js = r.read().decode()
    return js.replace("</script>", "<\\/script>")


def main():
    data = json.loads((HERE / "schedule.json").read_text())
    overrides = json.loads((HERE / "overrides.json").read_text())
    overrides = [o for o in overrides if isinstance(o, dict)]
    parsed = app.parse_data(data)
    slots = app.unified_slots(data)
    members = sorted(data)
    weekday_busy = [
        [
            [p for p in members if any(app.overlaps(iv, s) for iv in parsed[p].get(app.DAYS[w], []))]
            for w in range(7)
        ]
        for s in slots
    ]
    build_monday = app.week_of(dt.date.today())
    payload = {
        "members": members,
        "slots": [list(s) for s in slots],
        "weekday_busy": weekday_busy,
        "overrides": overrides,
        "build_monday": build_monday.isoformat(),
        "today_offset": (dt.date.today() - build_monday).days,
    }
    html = (
        TEMPLATE
        .replace("__PLOTLY__", _plotly_js())
        .replace("__DATA__", json.dumps(payload, separators=(",", ":")).replace("</", "<\\/"))
    )
    (HERE / "schedule.html").write_text(html)
    print(f"wrote schedule.html ({len(html) // 1024} KB, {len(members)} RAs, {len(slots)} slots)")


if __name__ == "__main__":
    main()
